name: Deploy App (Frontend + Backend)

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

      # --- Build and Deploy Frontend (Static Web App) ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Build Frontend
        working-directory: frontend
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}
        run: |
          npm ci
          npm run build

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "build"
          action: "upload"

      # --- Deploy Backend (Function App) ---

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # âœ… Install Backend Dependencies before deploy
      - name: Install Backend Dependencies
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
          
      - name: Deploy Backend to Function App
        uses: azure/functions-action@v1
        with:
          app-name: "func-azure-monitoring-demo"  # ðŸ‘ˆ your Function App name
          package: "./api"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
